[2021-01-08T12:21:59.409750+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2021-01-08T12:21:59.421208+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-08T12:21:59.421220+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-08T12:21:59.421234+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-08T12:21:59.426157+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-08T12:21:59.510646+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)"} []
[2021-01-08T12:22:34.768793+01:00] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2021-01-08T12:22:34.778914+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-08T12:22:34.778927+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-08T12:22:34.778932+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-08T12:22:34.779114+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-01-08T12:22:34.827534+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in driver: could not find driver" at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 102 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)"} []
[2021-01-26T12:05:49.959663+01:00] console.ERROR: Error thrown while running command "'make:migration'". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at /home/souaguen/Bureau/harmonypresent/vendor/symfony/framework-bundle/EventListener/SuggestMissingPackageSubscriber.php:73)","command":"'make:migration'","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2021-01-26T12:07:53.877703+01:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2021-01-26T12:07:53.998784+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-26T12:07:53.998801+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T12:07:53.998810+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T12:07:54.257756+01:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-01-26T12:08:09.545842+01:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2021-01-26T12:08:09.547639+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-26T12:08:09.547650+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T12:08:09.547657+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T12:08:09.554029+01:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-01-26T13:03:40.276453+01:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2021-01-26T13:03:40.413204+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-26T13:03:40.413219+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T13:03:40.413228+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T13:03:40.761556+01:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-01-26T13:03:45.291294+01:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2021-01-26T13:03:45.293235+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-01-26T13:03:45.293274+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T13:03:45.293286+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-01-26T13:03:45.300643+01:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /home/souaguen/Bureau/harmonypresent/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-02-18T02:10:37.273349+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://www.harmony-promotion.com/public/","method":"GET"} []
[2021-02-18T02:10:37.302595+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-18T02:10:37.302605+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:10:37.302610+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:10:37.371410+00:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-02-18T02:10:37.404063+00:00] php.CRITICAL: Uncaught Error: Undefined constant "XML_PI_NODE" {"exception":"[object] (Error(code: 0): Undefined constant \"XML_PI_NODE\" at /var/www/html/var/cache/prod/ContainerFf338B5/get_Container_Private_SerializerService.php:27)"} []
[2021-02-18T02:10:37.405647+00:00] request.CRITICAL: Uncaught PHP Exception Error: "Undefined constant "XML_PI_NODE"" at /var/www/html/var/cache/prod/ContainerFf338B5/get_Container_Private_SerializerService.php line 27 {"exception":"[object] (Error(code: 0): Undefined constant \"XML_PI_NODE\" at /var/www/html/var/cache/prod/ContainerFf338B5/get_Container_Private_SerializerService.php:27)"} []
[2021-02-18T02:10:37.405855+00:00] php.CRITICAL: Uncaught Error: Undefined constant "XML_PI_NODE" {"exception":"[object] (Error(code: 0): Undefined constant \"XML_PI_NODE\" at /var/www/html/var/cache/prod/ContainerFf338B5/get_Container_Private_SerializerService.php:27)"} []
[2021-02-18T02:25:10.408668+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://harmony-promotion.com/public/","method":"GET"} []
[2021-02-18T02:25:10.416327+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-18T02:25:10.416337+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:25:10.416342+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:25:10.423476+00:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-02-18T02:25:15.961932+00:00] console.CRITICAL: Error thrown while running command "'make:migration'". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at /var/www/html/vendor/symfony/framework-bundle/EventListener/SuggestMissingPackageSubscriber.php:73)","command":"'make:migration'","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2021-02-18T02:25:30.106720+00:00] console.CRITICAL: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists" {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:57)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:125)","command":"doctrine:migrations:migrate","message":"An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists"} []
[2021-02-18T02:25:30.118765+00:00] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2021-02-18T02:26:10.993021+00:00] console.CRITICAL: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists" {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:57)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:125)","command":"doctrine:migrations:migrate","message":"An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists"} []
[2021-02-18T02:26:11.005998+00:00] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2021-02-18T02:31:40.284309+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://harmony-promotion.com/public/","method":"GET"} []
[2021-02-18T02:31:40.286482+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-18T02:31:40.286492+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:31:40.286497+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\CustomFormAuthenticator"} []
[2021-02-18T02:31:40.289746+00:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Repository\ProgrammeRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service"." at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php line 55 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Repository\\ProgrammeRepository\" entity repository implements \"Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepositoryInterface\", but its service could not be found. Make sure the service exists and is tagged with \"doctrine.repository_service\". at /var/www/html/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:55)"} []
[2021-02-18T02:33:11.721016+00:00] console.CRITICAL: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists" {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:57)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:125)","command":"doctrine:migrations:migrate","message":"An exception occurred while executing 'CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, numero INT NOT NULL, page VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'page' already exists"} []
[2021-02-18T02:33:11.733246+00:00] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
